import { SupportedLanguage } from './translations';
const copy = {
  en: {
    title: 'Understand your family’s inheritance shares.', intro: 'Add the estate, select the surviving family, and review the inheritance breakdown with its supporting evidence.',
    estate: 'Estate', family: 'Family', results: 'Shares', next: 'Continue to family', review: 'Review shares', back: 'Back to estate',
    welcome: 'A little clarity, at a difficult time.', welcomeBody: 'Mawarith helps you understand how an estate may be divided under Islamic inheritance rules. Work through it at your own pace.',
    start: 'Start my calculation', example: 'Try an example', help: 'How it works', steps: ['Add assets, costs, debts and any bequest.', 'Select relatives alive at the time of death.', 'Review each share and the evidence behind it.'],
    guidance: 'Use this as a starting point. Have a qualified scholar review your family’s circumstances before distributing an estate.',
    examples: 'Explore example cases', sample: 'Example calculation', sampleNote: 'These are example values. Start fresh to enter your own estate.', reset: 'Start fresh', undo: 'Undo reset', copy: 'Copy summary', copied: 'Summary copied', copyError: 'Could not copy. Please try again.',
    deductions: 'Costs, debts & bequest', deductionsHelp: 'These are deducted before the estate is divided.', secured: 'Secured debts', itemize: 'Add details', total: 'Use one total', add: 'Add item',
    moreFamily: 'Grandparents, grandchildren & other relatives', moreFamilyHelp: 'Include all surviving relatives, even if closer family members are present.', optionalNames: 'Add names (optional)', deceased: 'Name of the deceased (optional)', male: 'Male', female: 'Female',
    empty: 'Your breakdown will appear here', emptyHelp: 'Select surviving family members to see their shares. Add estate values to see the amounts.', each: 'each', evidence: 'View evidence', breakdown: 'Shares & their evidence', net: 'Available to distribute', remainder: 'Unallocated remainder', warning: 'Calculation notes', selected: 'selected', close: 'Close',
  },
  ar: {
    title: 'افهم أنصبة الميراث في أسرتك.', intro: 'أضف التركة، وحدد أفراد الأسرة الأحياء، ثم راجع أنصبة الميراث وأدلتها.',
    estate: 'التركة', family: 'الأسرة', results: 'الأنصبة', next: 'متابعة إلى الأسرة', review: 'مراجعة الأنصبة', back: 'العودة إلى التركة',
    welcome: 'وضوح يعينك في وقت صعب.', welcomeBody: 'تساعدك مواريث على فهم تقسيم التركة وفق أحكام الميراث الإسلامي. تابع الخطوات بالوتيرة المناسبة لك.', start: 'ابدأ حسابي', example: 'جرّب مثالاً', help: 'كيف يعمل؟', steps: ['أضف الأصول والتكاليف والديون والوصية.', 'حدد الأقارب الأحياء وقت الوفاة.', 'راجع كل نصيب والدليل عليه.'],
    guidance: 'هذا الحساب نقطة بداية. راجع ظروف أسرتك مع عالم مؤهل قبل توزيع التركة.', examples: 'استعراض أمثلة', sample: 'حساب توضيحي', sampleNote: 'هذه قيم توضيحية. ابدأ من جديد لإدخال تركتك.', reset: 'ابدأ من جديد', undo: 'تراجع عن المسح', copy: 'نسخ الملخص', copied: 'تم نسخ الملخص', copyError: 'تعذر النسخ. حاول مرة أخرى.',
    deductions: 'التكاليف والديون والوصية', deductionsHelp: 'تُخصم هذه المبالغ قبل تقسيم التركة.', secured: 'ديون مضمونة', itemize: 'إضافة تفاصيل', total: 'استخدام مبلغ إجمالي', add: 'إضافة بند', moreFamily: 'الأجداد والأحفاد والأقارب الآخرون', moreFamilyHelp: 'أضف جميع الأقارب الأحياء، حتى مع وجود أفراد الأسرة الأقرب.', optionalNames: 'إضافة أسماء (اختياري)', deceased: 'اسم المتوفى (اختياري)', male: 'ذكر', female: 'أنثى', empty: 'ستظهر الأنصبة هنا', emptyHelp: 'حدد أفراد الأسرة الأحياء لرؤية أنصبتهم، وأضف قيمة التركة لرؤية المبالغ.', each: 'لكل فرد', evidence: 'عرض الدليل', breakdown: 'الأنصبة وأدلتها', net: 'المتاح للتوزيع', remainder: 'المبلغ المتبقي غير الموزع', warning: 'ملاحظات الحساب', selected: 'محدد', close: 'إغلاق',
  },
  ur: {
    title: 'اپنے خاندان کے وراثتی حصے سمجھیں۔', intro: 'ترکہ درج کریں، زندہ اہلِ خانہ منتخب کریں، پھر دلائل کے ساتھ وراثت کے حصے دیکھیں۔', estate: 'ترکہ', family: 'خاندان', results: 'حصے', next: 'خاندان کی طرف بڑھیں', review: 'حصے دیکھیں', back: 'ترکہ پر واپس جائیں',
    welcome: 'مشکل وقت میں کچھ وضاحت۔', welcomeBody: 'مواریث اسلامی اصولوں کے مطابق ترکے کی تقسیم سمجھنے میں مدد کرتا ہے۔ اپنی سہولت کے مطابق آگے بڑھیں۔', start: 'اپنا حساب شروع کریں', example: 'ایک مثال دیکھیں', help: 'طریقۂ استعمال', steps: ['اثاثے، اخراجات، قرض اور وصیت درج کریں۔', 'وفات کے وقت زندہ رشتہ دار منتخب کریں۔', 'ہر حصہ اور اس کی دلیل دیکھیں۔'], guidance: 'یہ حساب ایک ابتدائی رہنمائی ہے۔ ترکہ تقسیم کرنے سے پہلے اپنے خاندان کے حالات کسی مستند عالم سے جانچوا لیں۔', examples: 'مثالی مسائل دیکھیں', sample: 'مثالی حساب', sampleNote: 'یہ مثالی اعداد ہیں۔ اپنا ترکہ درج کرنے کے لیے نیا حساب شروع کریں۔', reset: 'نیا حساب', undo: 'حساب بحال کریں', copy: 'خلاصہ کاپی کریں', copied: 'خلاصہ کاپی ہو گیا', copyError: 'کاپی نہیں ہو سکا۔ دوبارہ کوشش کریں۔', deductions: 'اخراجات، قرض اور وصیت', deductionsHelp: 'یہ رقوم ترکہ تقسیم کرنے سے پہلے منہا ہوتی ہیں۔', secured: 'ضمانت والے قرض', itemize: 'تفصیل شامل کریں', total: 'کل رقم درج کریں', add: 'اندراج شامل کریں', moreFamily: 'بزرگ، پوتے پوتیاں اور دیگر رشتہ دار', moreFamilyHelp: 'تمام زندہ رشتہ دار شامل کریں، چاہے قریبی اہلِ خانہ موجود ہوں۔', optionalNames: 'نام شامل کریں (اختیاری)', deceased: 'مرحوم کا نام (اختیاری)', male: 'مرد', female: 'عورت', empty: 'حصوں کی تفصیل یہاں ظاہر ہوگی', emptyHelp: 'حصے دیکھنے کے لیے زندہ اہلِ خانہ منتخب کریں۔ رقوم دیکھنے کے لیے ترکے کی مالیت درج کریں۔', each: 'فی فرد', evidence: 'دلیل دیکھیں', breakdown: 'حصے اور ان کے دلائل', net: 'تقسیم کے لیے دستیاب', remainder: 'غیر تقسیم شدہ باقی رقم', warning: 'حساب کے نوٹس', selected: 'منتخب', close: 'بند کریں',
  },
};
export const workflow = (language: SupportedLanguage) => copy[language];
